#ifndef _YAMAIL_CONCURRENCY_NAMESPACE_H_
#define _YAMAIL_CONCURRENCY_NAMESPACE_H_
#include <yamail/config.h>
#include <yamail/namespace.h>

#define YAMAIL_NS_CONCURRENCY concurrency
#define YAMAIL_FQNS_CONCURRENCY YAMAIL_FQNS::YAMAIL_NS_CONCURRENCY

#define YAMAIL_NS_CONCURRENCY_BEGIN namespace YAMAIL_NS_CONCURRENCY {
#define YAMAIL_NS_CONCURRENCY_END }

#define YAMAIL_FQNS_CONCURRENCY_BEGIN \
    YAMAIL_NS_BEGIN YAMAIL_NS_CONCURRENCY_BEGIN
#define YAMAIL_FQNS_CONCURRENCY_END YAMAIL_NS_CONCURRENCY_END YAMAIL_NS_END

#endif // _YAMAIL_CONCURRENCY_NAMESPACE_H_
