#ifndef _YAMAIL_CONCURRENCY_COROUTINE_H_
#define _YAMAIL_CONCURRENCY_COROUTINE_H_
#include <yamail/config.h>
#include <yamail/concurrency/namespace.h>

#define YAMAIL_NS_CONCURRENCY_COROUTINE coroutine /* ZeroCopy Buffers */
#define YAMAIL_FQNS_CONCURRENCY_COROUTINE \
  YAMAIL_FQNS_CONCURRENCY::YAMAIL_NS_CONCURRENCY_COROUTINE

#define YAMAIL_NS_CONCURRENCY_COROUTINE_BEGIN \
  namespace YAMAIL_NS_CONCURRENCY_COROUTINE {
#define YAMAIL_NS_CONCURRENCY_COROUTINE_END }

#define YAMAIL_FQNS_CONCURRENCY_COROUTINE_BEGIN \
  YAMAIL_NS_BEGIN YAMAIL_NS_CONCURRENCY_BEGIN \
  YAMAIL_NS_CONCURRENCY_COROUTINE_BEGIN

#define YAMAIL_FQNS_CONCURRENCY_COROUTINE_END \
  YAMAIL_NS_CONCURRENCY_COROUTINE_END YAMAIL_NS_CONCURRENCY_END YAMAIL_NS_END

#endif // _YAMAIL_CONCURRENCY_COROUTINE_H_
