#ifndef _YAMAIL_TRAITS_NAMESPACE_H_
#define _YAMAIL_TRAITS_NAMESPACE_H_
#include <yamail/config.h>
#include <yamail/namespace.h>

#define YAMAIL_NS_TRAITS traits
#define YAMAIL_FQNS_TRAITS YAMAIL_FQNS::YAMAIL_NS_TRAITS

#define YAMAIL_NS_TRAITS_BEGIN namespace YAMAIL_NS_TRAITS {
#define YAMAIL_NS_TRAITS_END }

#define YAMAIL_FQNS_TRAITS_BEGIN YAMAIL_NS_BEGIN YAMAIL_NS_TRAITS_BEGIN
#define YAMAIL_FQNS_TRAITS_END YAMAIL_NS_TRAITS_END YAMAIL_NS_END

#endif // _YAMAIL_TRAITS_NAMESPACE_H_
