#ifndef _YAMAIL_ITERATOR_NAMESPACE_H_
#define _YAMAIL_ITERATOR_NAMESPACE_H_
#include <yamail/config.h>
#include <yamail/namespace.h>

#define YAMAIL_NS_ITERATOR iterator
#define YAMAIL_FQNS_ITERATOR YAMAIL_FQNS::YAMAIL_NS_ITERATOR

#define YAMAIL_NS_ITERATOR_BEGIN namespace YAMAIL_NS_ITERATOR {
#define YAMAIL_NS_ITERATOR_END }

#define YAMAIL_FQNS_ITERATOR_BEGIN YAMAIL_NS_BEGIN YAMAIL_NS_ITERATOR_BEGIN
#define YAMAIL_FQNS_ITERATOR_END YAMAIL_NS_ITERATOR_END YAMAIL_NS_END

#endif // _YAMAIL_ITERATOR_NAMESPACE_H_
