#ifndef _YAMAIL_UTILITY_NAMESPACE_H_
#define _YAMAIL_UTILITY_NAMESPACE_H_
#include <yamail/config.h>
#include <yamail/namespace.h>

#define YAMAIL_NS_UTILITY utility
#define YAMAIL_FQNS_UTILITY YAMAIL_FQNS::YAMAIL_NS_UTILITY

#define YAMAIL_NS_UTILITY_BEGIN namespace YAMAIL_NS_UTILITY {
#define YAMAIL_NS_UTILITY_END }

#define YAMAIL_FQNS_UTILITY_BEGIN YAMAIL_NS_BEGIN YAMAIL_NS_UTILITY_BEGIN
#define YAMAIL_FQNS_UTILITY_END YAMAIL_NS_UTILITY_END YAMAIL_NS_END

#endif // _YAMAIL_UTILITY_NAMESPACE_H_
