#ifndef _YAMAIL_COMPAT_NAMESPACE_H_
#define _YAMAIL_COMPAT_NAMESPACE_H_
#include <yamail/config.h>
#include <yamail/compat/config.h>
#include <yamail/namespace.h>

#define YAMAIL_NS_COMPAT compat
#define YAMAIL_FQNS_COMPAT YAMAIL_FQNS::YAMAIL_NS_COMPAT

#define YAMAIL_NS_COMPAT_BEGIN namespace YAMAIL_NS_COMPAT {
#define YAMAIL_NS_COMPAT_END }

#define YAMAIL_FQNS_COMPAT_BEGIN YAMAIL_NS_BEGIN YAMAIL_NS_COMPAT_BEGIN
#define YAMAIL_FQNS_COMPAT_END YAMAIL_NS_COMPAT_END YAMAIL_NS_END

#endif // _YAMAIL_COMPAT_NAMESPACE_H_
